; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = m5stack-atom-lite

[env:native]
platform = native

[env:m5stack-atom-lite]
platform = espressif32
board = m5stack-atom
framework = arduino
lib_deps =
    M5Stack
;    m5stack/M5Atom
    fastled/FastLED
    painlessMesh
    TaskScheduler
    me-no-dev/AsyncTCP
; Why do I need to specify these in addition to M5Stack?!
#    arduinoespressif32
    Wire
    SPI
    FS
    SPIFFS
    SD
    HTTPClient
#    WiFiClient
    WiFi
    WifiClientSecure
    Update
;    JC_Button

;check_tool = clangtidy

; change microcontroller
board_build.mcu = esp32

; change MCU frequency
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L      ;80M, 40M
board_build.flash_mode = dio         ;qio, qout, dio, dout

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0             ;0:None, 1:Error, 2:Warn, 3:Info, 4:Debug, 5:Verbose
    -DARDUINO_RUNNING_CORE=1         ;0:Core0, 1:Core1(default)
    -DARDUINO_EVENT_RUNNING_CORE=1   ;0:Core0, 1:Core1(default)

upload_speed = 1500000   

upload_protocol = esptool